//This code was generated by llama3-8b running on my local machine.
#include <iostream>
using namespace std;

int main() {
    // Print top border
    for(int j = 0; j < 23; j++) {
        cout << "-";
     }
    cout << endl;

    // Print middle section
    for(int i = 1; i < 9; i++) {
        for(int j = 0; j < 22; j++) {
            if(j == 0 || j == 21) { // Print left or right border
                cout << "|";
             } else {
                cout << " ";
             }
         }
        cout << endl;
    }

    // Print bottom border
    for(int j = 0; j < 23; j++) {
        cout << "-";
     }
    cout << endl;

    return 0;
}